### ISSUE TITLE
Why is Celluloid need to be included in actor?

### ISSUE THREAD

**Issue by dsshap** [gzigzigzeo/sidekiq-grouping#7]
Why does actor require celluloid?

https://github.com/gzigzigzeo/sidekiq-grouping/blob/06c5a7651fb13db4d97d4f72a27667263bd6f2ac/lib/sidekiq/grouping/actor.rb#L5

**Comment by dsshap** [comment]
I have to then include 

```
require 'celluloid'
```

and then my workers dont seem to recognize other classes/workers:

uninitialized constant FooWorker.perform_async or BarModel.new

**Comment by dsshap** [comment]
I am using sinatra, not rails

**Comment by dsshap** [comment]
Bump

**Comment by skyshard** [comment]
Not sure why it's required, but I've seen a similar issue in this: https://github.com/brainopia/sidekiq-limit_fetch/pull/5

> sidekiq plugins should not load any sidekiq files which explicitly depend on celluloid (eg, include Celluloid), instead method hooks + autoloading can be used



https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/cli.rb#L157

**Comment by gzigzigzeo** [comment]
@dsshap Sorry for a delay, I was without internet for two weeks. It requires celluloid because of https://github.com/gzigzigzeo/sidekiq-grouping/blob/06c5a7651fb13db4d97d4f72a27667263bd6f2ac/lib/sidekiq/grouping/actor.rb#L15 Can you provide failing spec or something to make me able to reproduce your trouble? Is your issue the same as given by @skyshard for limit_fetch?

**Comment by dsshap** [comment]
I believe it is the same as @skyshard for limit_fetch.

I cant think of a quick spec to verify this. I have a sinatra app, with latest sidekiq. Trying to load another job or model from a running job fails when requiring celluloid.

Without requiring celluloid, the application will not start due to sidekiq-grouping compaining that celluloid isnt loaded.

**Comment by gzigzigzeo** [comment]
@dsshap Okay, seemed I understood the problem and know the way how to solve it. Celluloid is required only by Actor which is required only by Supervisor when running inside sidekiq server. It is not required in application itself. Autoload should fix the problem. I will try it tomorrow.

**Comment by dsshap** [comment]
@gzigzigzeo Great! Let me know when you push the change to GH and I will confirm on my end.

**Comment by gzigzigzeo** [comment]
@dsshap Try HEAD version from repo please. I've made all classes autoloadable. If Sidekiq is not running in server mode inside your app - it should work. https://github.com/gzigzigzeo/sidekiq-grouping/blob/master/lib/sidekiq/grouping.rb#L38

**Comment by dsshap** [comment]
@gzigzigzeo I didnt need to require celluloid, but I am still not able to reference other jobs or models from within the batched job.

**Comment by gzigzigzeo** [comment]
@dsshap https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/cli.rb#L158 Sidekiq requires Celluloid to not be loaded until some moment because of forking troubles. I think my gem now fits these requirement. Are you sure that your troubles are because of use sidekiq-grouping? Will your app work correctly without grouping in gemfile? If so - could you please try to change gem load order?

**Comment by gzigzigzeo** [comment]
@dsshap If you use Sinatra - are you sure that your models are in Sidekiq's load path? Could you try to require that unresolvable other workers and models within your worker class?

**Comment by gzigzigzeo** [comment]
@dsshap Could you provide any feedback, please?
